apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: camel-example-hystrix-service1-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    creationTimestamp: null
    labels:
      app: camel-example-hystrix-service1
      expose: "true"
      group: sample.camel
      provider: fabric8
      version: 1.0-SNAPSHOT
    name: camel-example-hystrix-service1
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: camel-example-hystrix-service1
      group: sample.camel
      provider: fabric8
    sessionAffinity: None
    type: ClusterIP
  status: []
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: camel-example-hystrix-service1
      expose: "true"
      group: sample.camel
      provider: fabric8
      version: 1.0-SNAPSHOT
    name: camel-example-hystrix-service1
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: camel-example-hystrix-service1
      weight: 100
    wildcardPolicy: None
  status: []
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: camel-example-hystrix-service1
      group: sample.camel
      provider: fabric8
      version: 1.0-SNAPSHOT
    name: camel-example-hystrix-service1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations: null
    creationTimestamp: null
    generation: 1
    labels:
      app: camel-example-hystrix-service1
      group: sample.camel
      provider: fabric8
      version: 1.0-SNAPSHOT
    name: camel-example-hystrix-service1
  spec:
    replicas: 1
    selector:
      app: camel-example-hystrix-service1
      group: sample.camel
      provider: fabric8
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations: null
        creationTimestamp: null
        labels:
          app: camel-example-hystrix-service1
          group: sample.camel
          provider: fabric8
          version: 1.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: JAVA_APP_DIR
            value: /deployments
          image: camel-example-hystrix-service1:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spring-boot
        from:
          kind: ImageStreamTag
          name: camel-example-hystrix-service1:latest
          namespace: hystrixdemo-developer
      type: ImageChange
  status: []
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: camel-example-hystrix-service1
      group: sample.camel
      provider: fabric8
      version: 1.0-SNAPSHOT
    name: camel-example-hystrix-service1-s2i
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output:
      to:
        kind: ImageStreamTag
        name: camel-example-hystrix-service1:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: service1
      git:
        uri: https://github.com/eformat/camel-example-hystrix.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: http://nexus.nexus.svc.cluster.local:8081/repository/maven-public/
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:latest
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: secret1
      type: GitHub
    - generic:
        secret: secret1
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status: []